CREATE TABLE "BANK" (
	"Name" char(30) NOT NULL UNIQUE,
	"Number" varchar(8) NOT NULL UNIQUE,
	CONSTRAINT BANK_pk PRIMARY KEY ("Number")
) ;



CREATE TABLE "BRANCH" (
	"IFSC" varchar(14) NOT NULL UNIQUE,
	"Location" varchar(30) NOT NULL UNIQUE,
	"Bnk_No" varchar(8) NOT NULL,
	CONSTRAINT BRANCH_pk PRIMARY KEY ("IFSC")
);


CREATE TABLE "TEMP_ADDRESS" (
	"House_no" varchar(10) NOT NULL,
	"City" varchar(20) NOT NULL,
	"Street" varchar(30) NOT NULL,
	"Cust_ID" varchar(14) NOT NULL
);

CREATE TABLE "PERMANENT_ADDRESS" (
	"House_no" varchar(10) NOT NULL,
	"City" varchar(20) NOT NULL,
	"Street" varchar(30) NOT NULL,
	"Cust_ID" varchar(14) NOT NULL
) ;


CREATE TABLE "ACCOUNT" (
	"Balance" DECIMAL NOT NULL,
	"Number" bigint(14) NOT NULL UNIQUE,
	"Type" varchar(20) NOT NULL,
	CONSTRAINT ACCOUNT_pk PRIMARY KEY ("Number")
) ;


CREATE TABLE "LOAN" (
	"Amount" DECIMAL NOT NULL,
	"Interest" DECIMAL NOT NULL DEFAULT '7',
	"Tenure" int NOT NULL,
	"Loan_ID" varchar(20) NOT NULL,
	"Collatral" varchar(100) NOT NULL,
	"Cust_ID" varchar(14) NOT NULL,
	CONSTRAINT LOAN_pk PRIMARY KEY ("Loan_ID")
) ;


CREATE TABLE "ATM" (
	"ATM_NO" int NOT NULL UNIQUE,
	"Card_Limit" int NOT NULL,
	"Cust_ID" varchar(14) NOT NULL,
	CONSTRAINT ATM_pk PRIMARY KEY ("ATM_NO")
) ;


CREATE TABLE "CUSTOMER" (
	"ID" varchar(14) NOT NULL UNIQUE,
	"Gender" char(1) NOT NULL,
	"Name" varchar(30) NOT NULL,
	"DOB" DATE NOT NULL,
	"Age" int NOT NULL,
	CONSTRAINT CUSTOMER_pk PRIMARY KEY ("ID")
) ;

CREATE TABLE "TRANSACTION" (
	"CHQ_DEP" DECIMAL NOT NULL,
	"CSH_DEP" int NOT NULL,
	"CSH_WID" int NOT NULL,
	"Cust_ID" varchar NOT NULL,
	"ATM_NO" int NOT NULL
) ;


CREATE TABLE "BR_ACC" (
	"IFSC" varchar(14) NOT NULL,
	"Acc_No" bigint(14) NOT NULL
) ;


CREATE TABLE "BR_LOAN" (
	"Loan_ID" varchar(20) NOT NULL,
	"IFSC" varchar(14) NOT NULL
) ;



ALTER TABLE "BRANCH" ADD CONSTRAINT "BRANCH_fk0" FOREIGN KEY ("Bnk_No") REFERENCES "BANK"("Number");

ALTER TABLE "TEMP_ADDRESS" ADD CONSTRAINT "TEMP_ADDRESS_fk0" FOREIGN KEY ("Cust_ID") REFERENCES "CUSTOMER"("ID");

ALTER TABLE "PERMANENT_ADDRESS" ADD CONSTRAINT "PERMANENT_ADDRESS_fk0" FOREIGN KEY ("Cust_ID") REFERENCES "CUSTOMER"("ID");


ALTER TABLE "LOAN" ADD CONSTRAINT "LOAN_fk0" FOREIGN KEY ("Cust_ID") REFERENCES "CUSTOMER"("ID");

ALTER TABLE "ATM" ADD CONSTRAINT "ATM_fk0" FOREIGN KEY ("Cust_ID") REFERENCES "CUSTOMER"("ID");


ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_fk0" FOREIGN KEY ("Cust_ID") REFERENCES "CUSTOMER"("ID");
ALTER TABLE "TRANSACTION" ADD CONSTRAINT "TRANSACTION_fk1" FOREIGN KEY ("ATM_NO") REFERENCES "ATM"("ATM_NO");

ALTER TABLE "BR_ACC" ADD CONSTRAINT "BR_ACC_fk0" FOREIGN KEY ("IFSC") REFERENCES "BRANCH"("IFSC");
ALTER TABLE "BR_ACC" ADD CONSTRAINT "BR_ACC_fk1" FOREIGN KEY ("Acc_No") REFERENCES "ACCOUNT"("Number");

ALTER TABLE "BR_LOAN" ADD CONSTRAINT "BR_LOAN_fk0" FOREIGN KEY ("Loan_ID") REFERENCES "LOAN"("Loan_ID");
ALTER TABLE "BR_LOAN" ADD CONSTRAINT "BR_LOAN_fk1" FOREIGN KEY ("IFSC") REFERENCES "BRANCH"("IFSC");

